import Head from 'next/head'

import BannerHome from '@/components/Banner';
import Footer from '@/components/Footer';
import ServicesHome from '@/components/ServiciosHome';
import Header from '@components/Header/index';



const HomePage = () => {
  return (
    <>
      <Head>
        <title>Guardian Security</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div>
          <Header />
          <BannerHome />
          <ServicesHome />
          <Footer />
        </div>
    </> 
  )
}

export default HomePage