import Header from '@components/Header'
import Footer from '@components/Footer'
import Head from 'next/head'


const Layout= ({children}) => {
  return (
    <div>
      <Head>
        <title>Guardian Security</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/LogoSinBack.png" />
      </Head>

        <Header />
        {children}
        <Footer />

    </div>
  )
}

export default Layout